### ISSUE TITLE
Possible Solutions?

### ISSUE THREAD

**Issue by JosephDuffy** [zssz/BugCoreBluetoothConnectivity#1]
Hi,

I have run in to this problem at my day job. We actually used this repo as an "it's not just us!" example :)

We eventually found out that pairing the devices (via an encrypted characteristic or L2CAP channel) stopped the issue from happening, but I believe that it still causes issues if you have a mix e.g. 1 device connected to 2 paired devices and 1 unpaired device will cause the 1 unpaired device to stop connecting to the first device. I've not had chance to 100% confirmed this though.

Have you learned anything further since publishing this repo? Any hunches you think may be worth knowing? I have planned to contact Apple about this but without an exact scenario that causes this I fear they won't be too helpful.

Thank you for open sourcing this!

**Comment by zssz** [comment]
Hi Joseph,

this code works as expected on devices with the iOS 12 beta installed. In
fact I was at WWDC this year and talked to the CoreBluetooth team and they
confirmed they have fixed it for iOS 12. The bug's radar number is/was:
37631857

**Comment by JosephDuffy** [comment]
Thanks for letting me know! We tried it and couldn't recreate the issue in the iOS 12 beta (public and developer). Great news 😀
